//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindDwh.ConceptualModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindModelContainer : DbContext
    {
        public NorthwindModelContainer()
            : base("name=NorthwindModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> CustomersSet { get; set; }
        public virtual DbSet<Employees> EmployeesSet { get; set; }
        public virtual DbSet<Orders> OrdersSet { get; set; }
        public virtual DbSet<Shippers> ShippersSet { get; set; }
        public virtual DbSet<OrderDetails> OrderDetailsSet { get; set; }
        public virtual DbSet<Products> ProductsSet { get; set; }
        public virtual DbSet<Categories> CategoriesSet { get; set; }
        public virtual DbSet<FactOrder> FactOrderSet { get; set; }
    }
}
